Repository CSID-DGU/2024-1-OSSP1-KoreanAlwaysEatRice-1, pull requests merged in 2024-05, with the labels that each got.

#9 [feat] 냉장고 재료 선택 및 저장 구현
  client/app/build.gradle.kts
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/RefrigeratorAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/add/AddIngredientBottomSheet.kt
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/add/AddIngredientViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/add/IngredientListAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/refrigerator/add/SharedPreferenceManager.kt
  client/app/src/main/res/color/selector_ingredient_text.xml
  client/app/src/main/res/drawable/selector_ingredient_background.xml
  client/app/src/main/res/layout/bottomsheet_ingredient.xml
  client/app/src/main/res/layout/fragment_refrigerator.xml
  client/app/src/main/res/layout/item_ingredient_list.xml
Labels: feat, pr

#40 [feat] 재료 가져오기 서버통신
  client/app/build.gradle.kts
  client/app/src/main/java/com/kaer/menuw/data/datasource/IngredientDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/IngredientDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponseGetIngredientDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/IngredientRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/IngredientService.kt
  client/app/src/main/java/com/kaer/menuw/di/ApiModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataSourceModule.kt
  client/app/src/main/java/com/kaer/menuw/di/RepositoryModule.kt
  client/app/src/main/java/com/kaer/menuw/di/RetrofitModule.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/Ingredient.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/IngredientRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/GetIngredientUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/HomeActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/HomeViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientBottomSheet.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuListActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuListViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuNotRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/MenuCategoryActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/MenuCategoryViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/recipe/CategoryRecipeFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/type/CategoryTypeFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/mypage/MyPage.kt
  client/app/src/main/java/com/kaer/menuw/presentation/onboarding/login/LogInViewModel.kt
Labels: feat, pr

#44 [feat] 메뉴 조리법 가져오기 서버통신
  client/app/src/main/java/com/kaer/menuw/data/datasource/MenuDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/MenuDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/request/RequestPostRecipeDto.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponsePostRecipeDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/MenuRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/MenuService.kt
  client/app/src/main/java/com/kaer/menuw/di/ApiModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataSourceModule.kt
  client/app/src/main/java/com/kaer/menuw/di/RepositoryModule.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/RecipeList.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/RecipeListItem.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/RecipeOrder.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/MenuRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/PostMenuRecipeUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuListViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuNotRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/RecommendMenuAdapter.kt
  client/app/src/main/res/layout/activity_recipe_page.xml
  client/app/src/main/res/layout/item_recipe_order.xml
Labels: feat, pr

#46 #45 fix 로그인 api 수정
  server/src/main/java/com/example/menuw/Exception/Exception404.java
  server/src/main/java/com/example/menuw/domain/User.java
  server/src/main/java/com/example/menuw/dto/ResponseDto/ResponseDto.java
  server/src/main/java/com/example/menuw/dto/ResponseDto/TokenDto.java
  server/src/main/java/com/example/menuw/dto/UserDto.java
  server/src/main/java/com/example/menuw/repository/UserRepository.java
  server/src/main/java/com/example/menuw/service/CustomUserDetailService.java
  server/src/main/java/com/example/menuw/service/KakaoAuthService.java
  server/src/main/java/com/example/menuw/service/KakaoUserInfo.java
  server/src/main/java/com/example/menuw/web/AuthController.java
  server/src/main/java/com/example/menuw/web/RecipeApiController.java
  server/src/main/java/com/example/menuw/web/S3ImageController.java
Labels: fix

#56 [feat] 내 정보 가져오기 API 개발
  .gitignore
  server/build.gradle
  server/src/main/java/com/example/menuw/dto/KakaoDto/KakaoAccount.java
  server/src/main/java/com/example/menuw/dto/KakaoDto/KakaoProfile.java
  server/src/main/java/com/example/menuw/dto/KakaoDto/KakaoProperties.java
  server/src/main/java/com/example/menuw/dto/KakaoDto/KakaoUserInfoResponse.java
  server/src/main/java/com/example/menuw/dto/KakaoProfile.java
  server/src/main/java/com/example/menuw/dto/ResponseDto/MyPageUserInfoDto.java
  server/src/main/java/com/example/menuw/service/KakaoAuthService.java
  server/src/main/java/com/example/menuw/service/KakaoUserInfo.java
  server/src/main/java/com/example/menuw/web/MyPageController.java
Labels: feat, fix
