Repository CSID-DGU/2024-1-OSSP1-KoreanAlwaysEatRice-1, pull requests merged in 2024-06, with the labels that each got.

#65 [fix] 메뉴 평가하기 API 수정
  server/build.gradle
  server/src/main/java/com/example/menuw/config/RedisRepositoryConfig.java
  server/src/main/java/com/example/menuw/domain/Menu.java
  server/src/main/java/com/example/menuw/dto/MenuDto.java
  server/src/main/java/com/example/menuw/dto/MenuSimpleDto.java
  server/src/main/java/com/example/menuw/repository/MenuRepository.java
  server/src/main/java/com/example/menuw/service/JwtAuthFilter.java
  server/src/main/java/com/example/menuw/service/JwtTokenProvider.java
  server/src/main/java/com/example/menuw/service/KakaoAuthService.java
  server/src/main/java/com/example/menuw/service/MenuService.java
  server/src/main/java/com/example/menuw/service/RecipeApiService.java
  server/src/main/java/com/example/menuw/service/UserService.java
  server/src/main/java/com/example/menuw/web/MenuController.java
  server/src/main/java/com/example/menuw/web/MyPageController.java
  server/src/main/java/com/example/menuw/web/RefrigeratorController.java
Labels: fix, pr

#68 [fix] 사용자 정보 가져오기 API 수정
  server/src/main/java/com/example/menuw/dto/KakaoDto/KakaoUnlinkResponse.java
  server/src/main/java/com/example/menuw/dto/UserDto.java
  server/src/main/java/com/example/menuw/service/KakaoAuthService.java
  server/src/main/java/com/example/menuw/web/MyPageController.java
Labels: fix, pr

#69 [feat] 회원 탈퇴 API 구현
  server/src/main/java/com/example/menuw/service/KakaoAuthService.java
  server/src/main/java/com/example/menuw/web/MyPageController.java
Labels: feat, pr

#48 [feat] 로그인 서버통신
  client/app/build.gradle.kts
  client/app/src/main/java/com/kaer/menuw/data/datasource/LogInDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/TokenDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/LogInDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponsePostLogInDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/LogInRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/TokenRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/LogInService.kt
  client/app/src/main/java/com/kaer/menuw/di/ApiModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataSourceModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataStoreModule.kt
  client/app/src/main/java/com/kaer/menuw/di/RepositoryModule.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/Token.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/LogInRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/TokenRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/GetTokenUseCase.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/PostLogInUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/onboarding/login/LogInViewModel.kt
  client/build.gradle.kts
Labels: feat, pr

#59 [feat] 좋게 평가한 메뉴 리스트 가져오기 서버통신
  client/app/src/main/java/com/kaer/menuw/data/datasource/MenuDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/MenuDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponseGetLikeMenuListDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/MenuRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/MenuService.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/LikeMenu.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/MenuRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/GetLikeMenuListUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListViewModel.kt
  client/app/src/main/res/layout/fragment_like_menu_list.xml
  client/app/src/main/res/layout/item_like_menu.xml
  client/app/src/main/res/values/strings.xml
Labels: feat, pr

#73 [feat] 추천 메뉴 리스트 가져오기 서버통신
  client/app/src/main/java/com/kaer/menuw/data/datasource/MenuDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/MenuDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/request/RequestPostRecommendMenuListDto.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponsePostRecommendMenuListDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/MenuRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/MenuService.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/RecommendMenu.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/MenuRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/PostRecommendMenuListUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuListActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuListViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuNotRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/MenuRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/MenuCategoryActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/MenuCategoryViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/model/RecommendRequestIntent.kt
  client/app/src/main/res/layout/item_recommend_menu.xml
  client/app/src/main/res/values/strings.xml
Labels: feat, pr

#74 [feat] 메뉴 평가하기 서버통신
  client/app/src/main/java/com/kaer/menuw/data/datasource/MenuDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/MenuDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/request/RequestPatchMenuLikeDto.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponsePatchMenuLikeDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/MenuRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/MenuService.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/MenuRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/PatchMenuLikeUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/menurecipe/RecipePageViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/util/DoubleDialog.kt
  client/app/src/main/java/com/kaer/menuw/util/SingleDialog.kt
  client/app/src/main/java/com/kaer/menuw/util/base/BaseDialog.kt
  client/app/src/main/res/layout/dialog_double.xml
  client/app/src/main/res/layout/dialog_single.xml
Labels: feat, pr

#77 [feat] 내 정보 가져오기 서버통신
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/kaer/menuw/data/datasource/InfoDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/StoredUserDataSource.kt
  client/app/src/main/java/com/kaer/menuw/data/datasource/impl/InfoDataSourceImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponseGetUserInfoDto.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/InfoRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/repository/StoredUserRepositoryImpl.kt
  client/app/src/main/java/com/kaer/menuw/data/service/InfoService.kt
  client/app/src/main/java/com/kaer/menuw/di/ApiModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataSourceModule.kt
  client/app/src/main/java/com/kaer/menuw/di/DataStoreModule.kt
  client/app/src/main/java/com/kaer/menuw/di/RepositoryModule.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/UserInfo.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/InfoRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/repository/StoredUserRepository.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/GetStoredUserInfoUseCase.kt
  client/app/src/main/java/com/kaer/menuw/domain/usecase/GetUserInfoUseCase.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/HomeActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/HomeViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/mypage/MyPage.kt
  client/app/src/main/java/com/kaer/menuw/presentation/mypage/MyPageActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/mypage/MyPageViewModel.kt
  client/app/src/main/res/layout/activity_home.xml
  client/app/src/main/res/layout/activity_mypage.xml
  client/app/src/main/res/values/strings.xml
Labels: feat, pr

#78 [feat] 각종 기능 수정 및 추가 구현
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/kaer/menuw/data/model/remote/response/ResponseGetLikeMenuListDto.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/LikeMenu.kt
  client/app/src/main/java/com/kaer/menuw/domain/entity/RefrigeratorIngredientItem.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/likemenu/LikeMenuListViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/IngredientListAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/IngredientTypeAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/SharedPreferenceManager.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/checkdate/GetExpiryDateBottomSheet.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/recipe/CategoryRecipeAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/recommend/category/type/CategoryTypeAdapter.kt
  client/app/src/main/res/drawable/selector_ingredient_edit_btn.xml
  client/app/src/main/res/drawable/selector_recipe_background.xml
  client/app/src/main/res/drawable/shape_background_fill_top15_rect.xml
  client/app/src/main/res/drawable/shape_bright_fill_5_rect.xml
  client/app/src/main/res/drawable/shape_green2_bright_fill_3_rect.xml
  client/app/src/main/res/drawable/shape_green2_bright_fill_5_rect.xml
  client/app/src/main/res/layout/activity_add_ingredient.xml
  client/app/src/main/res/layout/bottomsheet_get_expiry_date.xml
  client/app/src/main/res/layout/dialog_double.xml
  client/app/src/main/res/layout/dialog_single.xml
  client/app/src/main/res/layout/fragment_category_recipe.xml
  client/app/src/main/res/layout/fragment_refrigerator.xml
  client/app/src/main/res/layout/item_category_recipe.xml
  client/app/src/main/res/layout/item_category_type.xml
  client/app/src/main/res/layout/item_ingredient_list.xml
  client/app/src/main/res/layout/item_ingredient_refrigerator.xml
  client/app/src/main/res/layout/item_ingredient_type.xml
  client/app/src/main/res/layout/item_like_menu.xml
  client/app/src/main/res/values/colors.xml
Labels: feat, fix, pr

#80 [feat] 기능 추가 및 UI 수정
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/kaer/menuw/presentation/home/HomeActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/RefrigeratorFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/home/refrigerator/add/AddIngredientViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/menurecipe/RecipePageActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/menurecipe/RecipePageAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/menurecipe/RecipePageViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/onboarding/login/LogInActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/onboarding/splash/SplashActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/LoadingIndicator.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/MenuListActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/MenuListViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/MenuNotRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/MenuRecommendFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/RecommendMenuAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/MenuCategoryActivity.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/MenuCategoryViewModel.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/model/RecommendRequestIntent.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/recipe/CategoryRecipeAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/recipe/CategoryRecipeFragment.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/type/CategoryTypeAdapter.kt
  client/app/src/main/java/com/kaer/menuw/presentation/recommend/category/type/CategoryTypeFragment.kt
  client/app/src/main/java/com/kaer/menuw/util/Context.kt
  client/app/src/main/res/drawable/ic_notice.xml
  client/app/src/main/res/drawable/menuw_logo.png
  client/app/src/main/res/layout/activity_login.xml
  client/app/src/main/res/layout/activity_menu_list.xml
  client/app/src/main/res/layout/dialog_double.xml
  client/app/src/main/res/layout/dialog_single.xml
  client/app/src/main/res/layout/fragment_refrigerator.xml
  client/app/src/main/res/layout/item_ingredient_refrigerator.xml
  client/app/src/main/res/layout/item_recipe_order.xml
  client/app/src/main/res/layout/item_recommend_menu.xml
  client/app/src/main/res/layout/loading_indicator.xml
  client/app/src/main/res/values/themes.xml
Labels: feat, pr
